version: '2'
services:
  db:
    image: postgres:12-alpine
    networks: ["local_net"]
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  backend:
#    build: .
    image: dataoct/blog-backend
    networks:
      - local_net
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    image: dataoct/blog-frontend
    networks:
      - local_net
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
networks:
  local_net:
    driver: bridge
